apiVersion: v1
kind: Namespace
metadata:
  name: h2o
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: h2o-sa
  namespace: h2o
  annotations:
    iam.gke.io/gcp-service-account: kfx-user@<PROJECT_ID>.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2o
  namespace: h2o
  labels:
    app: h2o
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h2o
  template:
    metadata:
      labels:
        app: h2o
        version: "3"
    spec:
      containers:
        - name: h2o
          image: gcr.io/<PROJECT_ID>/kubeflow/h2o3:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 54321
              protocol: TCP
              name: h2o-port
          resources:
            requests:
              memory: "1500Mi"
              cpu: 1
            limits:
              memory: "4000Mi"
              cpu: 2
      serviceAccountName: h2o-sa
---
apiVersion: v1
kind: Service
metadata:
  name: h2o-svc
  namespace: h2o
  labels:
    app: h2o
spec:
  ports:
    - name: http
      port: 54321
      protocol: TCP
      targetPort: h2o-port
  selector:
    app: h2o
  type: ClusterIP